// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel LoadEXRTexture

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

Texture2D<float4> _ExrTexture;


int _Width;
int _Height;

RWStructuredBuffer<float3> _PositionBuffer;

[numthreads(8,8,1)]
void LoadEXRTexture(uint3 id : SV_DispatchThreadID)
{

    if(id.x >= _Width || id.y >= _Height) return;
    float2 uv = float2(id.x / (float)_Width, id.y / (float)_Height);
    float4 data = _ExrTexture.Load(uint3(id.x, id.y, 0));
    float3 position = data.rgb;
    uint index = id.x + id.y * _Width;
    _PositionBuffer[index] = position;
}
